[package]
name = "daena-plugin-host-fuzz"
version = "0.0.0"
publish = false
edition = "2021"
license = "Apache-2.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
daena-plugin-host = { path = ".." }

[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "verify_archive"
path = "fuzz_targets/verify_archive.rs"
test = false
doc = false
bench = false
