export type { MapDocument } from "./model";
export {
  cloneCollection,
  cloneDescriptor,
  cloneDocument,
  cloneLayers,
  createMapDocument,
  documentByteSize,
  documentHash,
  findFeature,
  findLayer,
  nextLayerOrder,
  removeFeatures,
  replaceFeature,
} from "./model";
export { CommandStack, type CommandStackSnapshot } from "./command-stack";
export type { FeatureMetadataPatch, MapCommand, MapCommandKind } from "./commands";
export {
  addBackgroundCommand,
  applyCommand,
  buildCreateLayer,
  buildCreateRasterLayer,
  buildDuplicateLayer,
  calibrateImageToWorld,
  calibrateWorldUnits,
  captureDeleteFeatures,
  captureReplaceCollection,
  createFeatureCommand,
  createLayerCommand,
  deleteFeaturesCommand,
  deleteLayerCommand,
  duplicateFeaturesCommand,
  duplicateLayerCommand,
  layersFieldValue,
  listedBackgrounds,
  moveFeaturesToLayerCommand,
  newRasterLayer,
  newVectorLayer,
  nextBackgroundOrder,
  removeBackgroundCommand,
  renameLayerCommand,
  reorderBackgroundCommand,
  reorderLayerCommand,
  reorderLayersByIdsCommand,
  replaceBackgroundCommand,
  replaceCollectionCommand,
  replaceGeometryCommand,
  setBackgroundOpacityCommand,
  setBackgroundVisibilityCommand,
  setCoordinateSpaceCommand,
  setDefaultViewCommand,
  setFeatureMetadataCommand,
  setFeaturesMetadataCommand,
  setFeaturesMetadataByIdCommand,
  setLayerLockedCommand,
  setLayerOpacityCommand,
  setLayerStyleCommand,
  setLayerVisibilityCommand,
  applyGeometryOperationCommand,
  setSnapSettingsCommand,
  snapEnabledFromDescriptor,
} from "./commands";
export {
  DEFAULT_WORLD_SPACE,
  PHYSICAL_COORDINATE_SPACE,
  authoredToNormalized,
  backgroundsFromDescriptor,
  coordinateSpaceFromDescriptor,
  coordinateSpaceKey,
  defaultViewFromDescriptor,
  duplicateOffset,
  extentOf,
  isOpenLayersDescriptor,
  normalizedToAuthored,
} from "./coordinate-space";
export {
  measurementSummary,
  unitsForCoordinateSpace,
  measureFeature,
  formatMeasurement,
  pathLength,
  polygonArea,
  pointDistance,
} from "./measurement";
export {
  runGeometryOperation,
  canRunOperation,
  operationLabel,
  type GeometryOperationKind,
  type GeometryOpParams,
  type GeometryOpResult,
} from "./geometry-operations";
export { buildPreview, commitSelectionIds, type GeometryPreview } from "./geometry-preview";
export { emptySelection, selectionFromIds, selectionHas, toggleSelectionId, type SelectionState } from "./selection";
export {
  buildMapSearchIndex,
  searchMapFeatures,
  type MapFeatureSearchEntry,
  type MapFeatureSearchResult,
} from "./map-search";
export {
  buildRecoveryPackage,
  contentHashForCollection,
  encodeGeoJsonBytes,
  encodeLayersField,
  recoveryPackageBytes,
  type MapEditDraftPackage,
} from "./persistence";
