/* eslint-disable */
/**
 * GENERATED CONTRACT TYPES.
 * Source schemas: schemas/plugin-manifest-v1.json and schemas/plugin-rpc-v1.json.
 * Do not edit this file by hand; regenerate it when the schema version changes.
 */

export type PluginKind = "declarative" | "sandboxed";
export type FieldType = "text" | "number" | "boolean" | "date" | "enum" | "entity-ref" | "relationship";

export interface Entrypoints { ui?: string; wasm?: string }
export interface Dependency { version: string; required: boolean }
export interface FieldDefinition { key: string; label: string; type: FieldType; required?: boolean; options?: string[]; entityTypes?: string[]; relationshipType?: string; targetEntityTypes?: string[]; shared?: boolean }
export interface SchemaContribution { namespace: string; entityTypes: string[]; fields: FieldDefinition[] }
export interface EntityTemplate { id: string; name: string; entityType: string; description?: string; icon?: string; fields: Record<string, unknown>; requiredFields?: string[]; document?: string }
export type MigrationOperation =
  | { kind: "create-namespace"; namespace: string }
  | { kind: "add-field"; namespace: string; field: FieldDefinition }
  | { kind: "rename-field"; namespace: string; from: string; to: string }
  | { kind: "drop-field"; namespace: string; key: string };
export interface Migration { id: string; from: number; to: number; recovery: "backup" | "preserve-data"; operations: MigrationOperation[] }
export type ViewComponent =
  | { type: "heading"; id: string; text: string }
  | { type: "text"; id: string; text: string }
  | { type: "entity-list"; id: string; title: string; entityType: string; limit: number }
  | { type: "entity-detail"; id: string; title: string; source: string }
  | { type: "field-form"; id: string; title: string; source: string; namespace: string; fields: string[]; editable: boolean }
  | { type: "button"; id: string; label: string; command: string };
export interface View { id: string; title: string; components?: ViewComponent[] }
export type CommandAction = { type: "refresh-view" };
export type CommandExposure = "view" | "broker";
export type CommandValueType = "object" | "string" | "number" | "boolean" | "array" | "null";
export interface CommandProperty { type: CommandValueType }
export interface CommandSchema {
  type: "object";
  properties?: Record<string, CommandProperty>;
  required?: string[];
  additionalProperties?: boolean;
}
export interface Command {
  id: string;
  title: string;
  action?: CommandAction;
  input?: CommandSchema;
  output?: CommandSchema;
  capabilities?: string[];
  exposure?: CommandExposure[];
}
export interface Service { name: string; major: number }
export interface Event { name: string; version: number }
export interface Services { provides: Service[]; consumes: Service[] }
export interface Events { publishes: Event[]; subscribes: Event[] }

export interface PluginManifest {
  manifestVersion: 1;
  id: string;
  name: string;
  version: string;
  publisher: string;
  hostApi: string;
  kind: PluginKind;
  entrypoints: Entrypoints;
  capabilities: string[];
  dependencies: Record<string, Dependency>;
  namespaces: string[];
  schemas: SchemaContribution[];
  templates: EntityTemplate[];
  views: View[];
  commands: Command[];
  services: Services;
  events: Events;
  migrations: Migration[];
}

export interface RpcRequest { rpcVersion: 1; sessionId: string; requestId: string; method: string; payload: unknown }
export interface RpcError { code: string; message: string; retryable: boolean; details?: unknown }
export type PluginRpcError = RpcError;
export interface RpcSuccess { rpcVersion: 1; requestId: string; ok: true; result: unknown }
export interface RpcFailure { rpcVersion: 1; requestId: string; ok: false; error: RpcError }
export type RpcResponse = RpcSuccess | RpcFailure;

export interface PluginBootstrap {
  rpcVersion: 1;
  pluginId: string;
  sessionId: string;
  projectId: string;
  version: string;
  hostApi: string;
  grantedCapabilities: string[];
  optionalFeatures: string[];
}

export interface EntityRecord {
  id: string;
  name: string;
  entityType: string | null;
  deleted: boolean;
  createdAt: string;
  updatedAt: string;
  revision: string;
}

export interface MutationOptions { expectedRevision?: string; requestId?: string }
export interface RevisionedEntityPayload { id: string; expectedRevision: string }
export interface RevisionedDocumentPayload { entityId: string; body: string; format?: string; expectedRevision: string }
export interface RevisionedFieldPayload { entityId: string; namespace: string; key: string; value: unknown; expectedRevision: string }
export interface RevisionedRelationshipPayload { id: string; expectedRevision: string }
export interface RevisionedAssetPayload { entityId: string; namespace: string; filename: string; contentHash: string; size: number; mimeType: string; path: string; expectedRevision: string }
export interface EntityCreateDocument { body: string; format?: string }
export interface EntityCreateField { namespace: string; key: string; value: unknown }
export interface EntityCreateRelationship { relationship_type: string; target_ids: string[] }
export interface BrokerMethodPayloads {
  "entity.list": { entityType?: string };
  "entity.get": { id: string };
  "entity.create": { name: string; type?: string | null; fields?: EntityCreateField[]; relationships?: EntityCreateRelationship[]; document?: EntityCreateDocument };
  "entity.update": { id: string; name?: string | null; type?: string | null; expectedRevision: string };
  "entity.delete": { id: string; expectedRevision: string };
  "document.list": { entityId: string };
  "document.save": { entityId: string; body: string; format?: string; expectedRevision: string };
  "field.read": { entityId: string; namespace: string; key: string };
  "field.list": { entityId: string; namespace: string };
  "field.set": { entityId: string; namespace: string; key: string; value: unknown; expectedRevision: string };
  "relationship.list": { entityId: string };
  "relationship.create": { source_id: string; target_id: string; relationship_type: string; metadata?: string; expectedRevision: string };
  "relationship.delete": { id: string; expectedRevision: string };
  "asset.list": { entityId: string };
  "asset.register": { entity_id: string; namespace: string; filename: string; content_hash: string; size: number; mime_type: string; path: string; expectedRevision: string };
  "search.query": { query: string };
}
export type BrokerMethod = keyof BrokerMethodPayloads;

export interface MigrationAuthoringOptions {
  recovery?: Migration["recovery"];
  description?: string;
}

export type LifecycleState = "discovered" | "validated" | "installed" | "resolved" | "activating" | "active" | "deactivating" | "failed" | "quarantined" | "incompatible" | "uninstalling" | "removed";
