/* eslint-disable */
/**
 * GENERATED CONTRACT TYPES.
 * Source: crates/daena-plugin-api (Rust types -> schemas/*.json via gen-contract).
 * Generated by scripts/gen-plugin-contract.mjs; run `npm run gen:plugin-contract`.
 * Do not edit this file by hand.
 */

export type PluginKind = "declarative" | "sandboxed";
export type FieldType = "text" | "number" | "boolean" | "date" | "enum" | "oneof" | "relationship";
export interface Entrypoints { ui?: string; wasm?: string }
export interface Dependency { required: boolean; version: string }
export interface OneOfVariant { label: string; options?: string[] | null; type: "text" | "number" | "boolean" | "date" | "enum" | "oneof" | "relationship" }
export interface MetadataFieldDefinition { key: string; label: string; oneOf?: OneOfVariant[]; options?: string[] | null; required?: boolean | null; type: "text" | "number" | "boolean" | "date" | "enum" | "oneof" }
export type TimelineFieldRole = "point" | "start" | "end";
export type TimelineFieldLayer = "dates" | "lifelines";
export interface TimelineFieldContribution { group?: string | null; label?: string | null; layer?: TimelineFieldLayer | null; role: TimelineFieldRole }
export interface FieldDefinition { cardinality?: "one" | "many"; entityTypes?: string[]; key: string; label: string; metadataFields?: MetadataFieldDefinition[]; multiple?: boolean; oneOf?: OneOfVariant[]; options?: string[] | null; relationshipType?: string; required?: boolean | null; shared?: boolean; targetEntityTypes?: string[]; timeline?: TimelineFieldContribution; type: FieldType }
export interface SchemaContribution { entityTypes: string[]; fields: FieldDefinition[]; namespace: string }
export interface EntityTemplate { description?: string | null; document?: string | null; entityType: string; fields: Record<string, unknown>; icon?: string | null; id: string; name: string; requiredFields?: string[] | null }
export type MigrationOperation = { kind: "create-namespace"; namespace: string } | { field: FieldDefinition; kind: "add-field"; namespace: string } | { from: string; kind: "rename-field"; namespace: string; to: string } | { key: string; kind: "drop-field"; namespace: string };
export interface Migration { from: number; id: string; operations: MigrationOperation[]; recovery: "backup" | "preserve-data"; to: number }
export type ViewComponent = { id: string; text: string; type: "heading" } | { id: string; text: string; type: "text" } | { entityType: string; id: string; limit: number; title: string; type: "entity-list" } | { id: string; source: string; title: string; type: "entity-detail" } | { editable: boolean; fields: string[]; id: string; namespace: string; source: string; title: string; type: "field-form" } | { command: string; id: string; label: string; type: "button" };
export type ViewRenderer = { type: "declarative" } | { type: "sandboxed" } | { id: string; major: number; type: "host-surface" };
export interface View { components?: ViewComponent[]; id: string; renderer?: ViewRenderer; title: string }
export type CommandAction = { type: "refresh-view" };
export type CommandExposure = "view" | "broker";
export type CommandValueType = "object" | "string" | "number" | "boolean" | "array" | "null";
export interface CommandProperty { type: CommandValueType }
export interface CommandSchema { additionalProperties?: boolean; properties?: Record<string, CommandProperty>; required?: string[]; type: "object" }
export interface Command { action?: CommandAction; capabilities?: string[]; exposure?: CommandExposure[]; id: string; input?: CommandSchema | null; output?: CommandSchema | null; title: string }
export type PluginStability = "stable" | "beta" | "experimental";
export interface Service { major: number; name: string }
export interface Event { name: string; version: number }
export interface Services { consumes: Service[]; provides: Service[] }
export interface Events { publishes: Event[]; subscribes: Event[] }
export interface PluginManifest { capabilities: string[]; commands: Command[]; dependencies: Record<string, Dependency>; enabledByDefault?: boolean; entrypoints: Entrypoints; events: Events; hostApi: string; id: string; kind: PluginKind; manifestVersion: 1; migrations: Migration[]; name: string; namespaces: string[]; publisher: string; schemas: SchemaContribution[]; services: Services; stability?: PluginStability; templates: EntityTemplate[]; version: string; views: View[] }

export interface RpcRequest { rpcVersion: 1; sessionId: string; requestId: string; method: string; payload: unknown }
export interface RpcError { code: string; details?: unknown; message: string; retryable: boolean }
export type PluginRpcError = RpcError;
export interface RpcSuccess { rpcVersion: 1; requestId: string; ok: true; result: unknown }
export interface RpcFailure { rpcVersion: 1; requestId: string; ok: false; error: RpcError }
export type RpcResponse = RpcSuccess | RpcFailure;
export interface PluginBootstrap { grantedCapabilities: string[]; hostApi: string; optionalFeatures: string[]; pluginId: string; projectId: string; rpcVersion: number; sessionId: string; version: string }
export interface EntityRecord { createdAt: string; deleted: boolean; entityType?: string | null; id: string; name: string; revision: string; updatedAt: string }
export interface EntityTypeCountRecord { count: number; entityType?: string | null }
export interface EntityPageRecord { hasMore: boolean; items: EntityRecord[]; limit: number; offset: number; total: number; typeCounts: EntityTypeCountRecord[] }
export interface MutationOptions { expectedRevision?: string; requestId?: string }
export interface RevisionedEntityPayload { id: string; expectedRevision: string }
export interface RevisionedDocumentPayload { entityId: string; body: string; format?: string; expectedRevision: string }
export interface RevisionedFieldPayload { entityId: string; namespace: string; key: string; value: unknown; expectedRevision: string }
export interface RevisionedRelationshipPayload { id: string; expectedRevision: string }
export interface RevisionedAssetPayload { entityId: string; namespace: string; filename: string; contentHash: string; size: number; mimeType: string; path: string; expectedRevision: string }
export interface EntityCreateDocument { body: string; format?: string | null }
export interface EntityCreateField { key: string; namespace: string; value: unknown }
export interface EntityCreateRelationship { relationship_type: string; target_ids: string[] }
export type AiRetrievalMode = "none" | "explicit_only" | "related" | "project";
export interface AiRetrievalPolicyPayload { allowedSourceKinds: string[]; includeSharedFields: boolean; mode: AiRetrievalMode; passageCount: number; query?: string | null; relationshipDepth: number; seedIds: string[] }
export interface AiRequestIdPayload { requestId: string }
export interface AiRequestStartPayload { deadlineMs?: number | null; immediateContext: unknown; operation: string; outputContract?: unknown; retrievalPolicy?: AiRetrievalPolicyPayload | null; taskId: string; userInstruction: string }
export interface AssetDeletePayload { assetId: string; expectedRevision: string; namespace: string }
export interface AssetListPayload { entityId: string; namespace?: string | null }
export interface AssetReadBeginPayload { assetId: string; namespace: string }
export interface AssetRegisterPayload { content_hash: string; entity_id: string; expectedRevision: string; filename: string; mime_type: string; namespace: string; path: string; size: number }
export interface AssetReplaceBeginPayload { assetId: string; expectedRevision: string; mimeType: string; namespace: string; size: number }
export interface AssetReplaceCommitPayload { contentHash: string; handle: string }
export interface AssetTransferCancelPayload { handle: string }
export interface AssetMetadataUpdatePayload { assetId: string; expectedRevision: string; filename?: string | null; namespace: string; referenceScope?: string | null; role?: string | null }
export interface DocumentListPayload { entityId: string }
export interface DocumentSavePayload { body: string; entityId: string; expectedRevision: string; format?: string | null }
export interface EntityCreatePayload { document?: EntityCreateDocument | null; fields?: EntityCreateField[]; name: string; relationships?: EntityCreateRelationship[]; type?: string | null }
export interface EntityDeletePayload { expectedRevision: string; id: string }
export interface EntityGetPayload { id: string }
export interface EntityListPayload { entityType?: string | null }
export interface EntityQueryPayload { entityTypes?: string[]; excludedEntityTypes?: string[]; limit?: number | null; offset?: number | null; query?: string | null; sortDirection?: "asc" | "desc" | null; sortField?: "name" | "createdAt" | "updatedAt" | "relevance" | null }
export interface EntityUpdatePayload { expectedRevision: string; id: string; name?: string | null; type?: string | null }
export interface EventTypePayload { type: string }
export interface EventPublishPayload { payload: unknown; type: string }
export interface FieldListPayload { entityId: string; namespace: string; sharedOnly?: boolean | null }
export interface FieldReadPayload { entityId: string; key: string; namespace: string }
export interface FieldSetPayload { entityId: string; expectedRevision: string; key: string; namespace: string; value: unknown }
export interface MapsAssetCreateBeginPayload { mapEntityId: string; mimeType?: string | null; size: number }
export interface MapsAssetCreateCommitPayload { contentHash: string; handle: string }
export interface MapsImageImportBeginPayload { filename: string; mimeType: string; name: string; size: number }
export interface MapsImageImportCommitPayload { contentHash: string; handle: string }
export interface MapsLayerCreatePayload { expectedRevision: string; kind?: string | null; mapEntityId: string; name: string }
export interface MapsLayerDeletePayload { expectedFeatureCount?: number | null; expectedRevision: string; expectedSourceRevision?: string | null; layerId: string; mapEntityId: string }
export interface MapsLayerUpdatePayload { defaultVisible?: boolean | null; expectedRevision: string; layerId: string; locked?: boolean | null; mapEntityId: string; name?: string | null; opacity?: number | null; order?: number | null; style?: unknown }
export interface MapsLocationsCreateAndLinkPayload { entityType: string; location: unknown; name: string }
export interface MapsLocationsListPayload { mapEntityId: string }
export interface MapsLocationsUnlinkPayload { entityId: string; locationId: string }
export interface MapsLocationsUpsertPayload { entityId: string; location: unknown }
export interface MapsPhysicalCreateBeginPayload { generation: unknown; name: string; size: number }
export interface MapsPhysicalCreateCommitPayload { contentHash: string; handle: string }
export interface MapsReconcileLinksPayload { mapEntityId: string }
export interface MapsRecoveryExportBeginPayload { mapEntityId: string; size: number }
export interface MapsRecoveryExportCommitPayload { contentHash: string; handle: string }
export interface MapsRecoveryListPayload { mapEntityId: string }
export interface MapsRecoveryRestorePayload { fileName: string; mapEntityId: string }
export interface MapsVectorCreateBeginPayload { generation: unknown; name: string; size: number }
export interface MapsVectorCreateCommitPayload { contentHash: string; handle: string }
export interface MapsVectorReplaceBeginPayload { assetId: string; expectedRevision: string; size: number }
export interface MapsVectorReplaceCommitPayload { contentHash: string; handle: string }
export interface RecordCreatePayload { collection: string; ownerEntityId: string; value: unknown }
export interface RecordDeletePayload { collection: string; expectedRevision: string; id: string; ownerEntityId: string }
export interface RecordListPayload { collection: string; homonymsOnly?: boolean | null; limit?: number | null; offset?: number | null; ownerEntityId: string; query?: string | null; sort?: string | null; status?: string | null; tag?: string | null }
export interface RecordUpdatePayload { collection: string; expectedRevision: string; id: string; ownerEntityId: string; value: unknown }
export interface RelationshipCreatePayload { expectedRevision: string; metadata?: string | null; relationship_type: string; source_id: string; target_id: string }
export interface RelationshipDeletePayload { expectedRevision: string; id: string; relationship_type?: string | null }
export interface RelationshipListPayload { entityId: string }
export interface RelationshipUpdatePayload { expectedRevision: string; id: string; metadata?: string | null; target_id?: string | null }
export interface SearchQueryPayload { query: string }
export interface ServiceCallPayload { deadlineMs?: number | null; major: number; name: string; payload: unknown }
export interface BrokerMethodPayloads {
  "ai.request.cancel": AiRequestIdPayload;
  "ai.request.citations": AiRequestIdPayload;
  "ai.request.poll": AiRequestIdPayload;
  "ai.request.result": AiRequestIdPayload;
  "ai.request.start": AiRequestStartPayload;
  "asset.delete": AssetDeletePayload;
  "asset.list": AssetListPayload;
  "asset.read.begin": AssetReadBeginPayload;
  "asset.register": AssetRegisterPayload;
  "asset.replace.begin": AssetReplaceBeginPayload;
  "asset.replace.commit": AssetReplaceCommitPayload;
  "asset.transfer.cancel": AssetTransferCancelPayload;
  "asset.update": AssetMetadataUpdatePayload;
  "document.list": DocumentListPayload;
  "document.save": DocumentSavePayload;
  "entity.create": EntityCreatePayload;
  "entity.delete": EntityDeletePayload;
  "entity.get": EntityGetPayload;
  "entity.list": EntityListPayload;
  "entity.query": EntityQueryPayload;
  "entity.update": EntityUpdatePayload;
  "event.poll": EventTypePayload;
  "event.publish": EventPublishPayload;
  "event.subscribe": EventTypePayload;
  "field.list": FieldListPayload;
  "field.read": FieldReadPayload;
  "field.set": FieldSetPayload;
  "maps.asset.create.begin": MapsAssetCreateBeginPayload;
  "maps.asset.create.commit": MapsAssetCreateCommitPayload;
  "maps.image.import.begin": MapsImageImportBeginPayload;
  "maps.image.import.commit": MapsImageImportCommitPayload;
  "maps.layer.create": MapsLayerCreatePayload;
  "maps.layer.delete": MapsLayerDeletePayload;
  "maps.layer.update": MapsLayerUpdatePayload;
  "maps.locations.create_and_link": MapsLocationsCreateAndLinkPayload;
  "maps.locations.list": MapsLocationsListPayload;
  "maps.locations.unlink": MapsLocationsUnlinkPayload;
  "maps.locations.upsert": MapsLocationsUpsertPayload;
  "maps.physical.create.begin": MapsPhysicalCreateBeginPayload;
  "maps.physical.create.commit": MapsPhysicalCreateCommitPayload;
  "maps.reconcile.links": MapsReconcileLinksPayload;
  "maps.recovery.export.begin": MapsRecoveryExportBeginPayload;
  "maps.recovery.export.commit": MapsRecoveryExportCommitPayload;
  "maps.recovery.list": MapsRecoveryListPayload;
  "maps.recovery.restore": MapsRecoveryRestorePayload;
  "maps.vector.create.begin": MapsVectorCreateBeginPayload;
  "maps.vector.create.commit": MapsVectorCreateCommitPayload;
  "maps.vector.replace.begin": MapsVectorReplaceBeginPayload;
  "maps.vector.replace.commit": MapsVectorReplaceCommitPayload;
  "record.create": RecordCreatePayload;
  "record.delete": RecordDeletePayload;
  "record.list": RecordListPayload;
  "record.update": RecordUpdatePayload;
  "relationship.create": RelationshipCreatePayload;
  "relationship.delete": RelationshipDeletePayload;
  "relationship.list": RelationshipListPayload;
  "relationship.update": RelationshipUpdatePayload;
  "search.query": SearchQueryPayload;
  "service.call": ServiceCallPayload;
}
export type BrokerMethod = keyof BrokerMethodPayloads;
export interface MigrationAuthoringOptions {
  recovery?: Migration["recovery"];
  description?: string;
}
export type LifecycleState = "discovered" | "validated" | "installed" | "resolved" | "activating" | "active" | "deactivating" | "failed" | "quarantined" | "incompatible" | "uninstalling" | "removed";
