/* eslint-disable */
/**
 * GENERATED CONTRACT TYPES.
 * Source schemas: schemas/plugin-manifest-v1.json and schemas/plugin-rpc-v1.json.
 * Do not edit this file by hand; regenerate it when the schema version changes.
 */

export type PluginKind = "declarative" | "sandboxed";
export type FieldType = "text" | "number" | "boolean" | "date" | "enum" | "entity-ref" | "relationship";

export interface Entrypoints { ui?: string; wasm?: string }
export interface Dependency { version: string; required: boolean }
export interface FieldDefinition { key: string; label: string; type: FieldType; required?: boolean; options?: string[]; entityTypes?: string[]; relationshipType?: string; targetEntityTypes?: string[] }
export interface SchemaContribution { namespace: string; entityTypes: string[]; fields: FieldDefinition[] }
export interface EntityTemplate { id: string; name: string; entityType: string; description?: string; icon?: string; fields: Record<string, unknown>; requiredFields?: string[]; document?: string }
export type MigrationOperation =
  | { kind: "create-namespace"; namespace: string }
  | { kind: "add-field"; namespace: string; field: FieldDefinition }
  | { kind: "rename-field"; namespace: string; from: string; to: string }
  | { kind: "drop-field"; namespace: string; key: string };
export interface Migration { id: string; from: number; to: number; recovery: "backup" | "preserve-data"; operations: MigrationOperation[] }
export interface View { id: string; title: string }
export interface Command { id: string; title: string }
export interface Service { name: string; major: number }
export interface Event { name: string; version: number }
export interface Services { provides: Service[]; consumes: Service[] }
export interface Events { publishes: Event[]; subscribes: Event[] }

export interface PluginManifest {
  manifestVersion: 1;
  id: string;
  name: string;
  version: string;
  publisher: string;
  hostApi: string;
  kind: PluginKind;
  entrypoints: Entrypoints;
  capabilities: string[];
  dependencies: Record<string, Dependency>;
  namespaces: string[];
  schemas: SchemaContribution[];
  templates: EntityTemplate[];
  views: View[];
  commands: Command[];
  services: Services;
  events: Events;
  migrations: Migration[];
}

export interface RpcRequest { rpcVersion: 1; sessionId: string; requestId: string; method: string; payload: unknown }
export interface RpcError { code: string; message: string; retryable: boolean; details?: unknown }
export type PluginRpcError = RpcError;
export interface RpcSuccess { rpcVersion: 1; requestId: string; ok: true; result: unknown }
export interface RpcFailure { rpcVersion: 1; requestId: string; ok: false; error: RpcError }
export type RpcResponse = RpcSuccess | RpcFailure;

export interface PluginBootstrap {
  rpcVersion: 1;
  pluginId: string;
  sessionId: string;
  projectId: string;
  version: string;
  hostApi: string;
  grantedCapabilities: string[];
  optionalFeatures: string[];
}

export interface EntityRecord {
  id: string;
  entityType: string;
  fields: Record<string, unknown>;
  document?: string;
}

export interface MigrationAuthoringOptions {
  recovery?: Migration["recovery"];
  description?: string;
}

export type LifecycleState = "discovered" | "validated" | "installed" | "resolved" | "activating" | "active" | "deactivating" | "failed" | "quarantined" | "incompatible" | "uninstalling" | "removed";
